# Generated by Django 6.0.3 on 2026-03-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stem", models.CharField(max_length=100, unique=True)),
                ("option_a", models.CharField(max_length=20)),
                ("option_b", models.CharField(max_length=20)),
                ("option_c", models.CharField(max_length=20)),
                ("option_d", models.CharField(max_length=20)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
