# Generated by Django 6.0.3 on 2026-03-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizattempt_attemptanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptanswer",
            name="shown_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="time_spent_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attemptanswer",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
